/chopper/state On
/chopper/material Uranium
/chopper/abundance 90
/mytar/abundance 90
/mytar/target Uranium
/control/verbose 0
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/chopper/thickness 30
/chopper/distance 2
/mydet/Angle 120
/mydet/attenuator Off
/mydet/attenuator2 Off
/mydet/nPMT 4
/mantistracking/track OpticalPhotons
/run/initialize

/vis/open VRML2FILE
/vis/viewer/set/autoRefresh false
/vis/drawVolume

/vis/scene/endOfEventAction accumulate 5000
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/invert true
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false
/vis/viewer/set/background 1 1 1

/vis/viewer/set/autoRefresh true
/run/beamOn 1000
